digital_marketplace/books/urls.py
from django.urls import path
from .views import book_list, book_detail, chapter_detail, exercise_detail
app_name='books'
urlpatterns = [
    path('', book_list, name='book-list'),
    path('<slug>/', book_detail, name='book-detail'),
    path('<book_slug>/<int:chapter_number>/', chapter_detail, name='chapter-detail'),
    path('<book_slug>/<int:chapter_number>/<exercise_number>',exercise_detail, name="exercise-detail")
]

digital_marketplace/digital_marketplace/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('shopping_cart.urls', namespace="cart"))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digital_marketplace/shopping_cart/urls.py
from django.urls import path
from .views import add_to_cart, remove_from_cart

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/<book_slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<book_slug>/', remove_from_cart, name='remove-from-cart')

]

digital_marketplace/books/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse, redirect
from django.db.models.signals import post_save


class UserLibrary(models.Model):
    books = models.ManyToManyField('Book', blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
    def book_list(self):
        return self.books.all()

    class Meta:
        verbose_name = 'User Library'
        verbose_name_plural = 'User Library'

def post_user_signup_receiver(sender,instance,created,*args,**kwargs):
    if created:
        UserLibrary.objects.get_or_create(user=instance)

post_save.connect(post_user_signup_receiver, sender=settings.AUTH_USER_MODEL)

class Author(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    slug= models.SlugField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Book(models.Model):
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=20)
    publication_date = models.DateTimeField()
    isbn= models.CharField(max_length=16)
    price = models.FloatField()
    slug = models.SlugField()
    cover = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book-detail", kwargs={"slug": self.slug})
    

class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:chapter-detail", kwargs={"book_slug": self.book.slug, 
        "chapter_number": self.chapter_number})
    

class Exercise(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    exercise_number = models.IntegerField()
    page_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:exercise-detail", kwargs={"book_slug": self.chapter.book.slug,
        "chapter_number": self.chapter.chapter_number,
        "exercise_number": self.exercise_number})
    

class Solution(models.Model):
    exercise= models.ForeignKey(Exercise, on_delete=models.CASCADE)
    solution_number= models.IntegerField()
    image= models.ImageField()

    def __str__(self):
        return f'{self.exercise}-{self.pk}'
    
    

    

digital_marketplace/shopping_cart/models.py
from django.db import models
from books.models import Book
from django.conf import settings

class OrderItem(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.book.title
    
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    is_ordered = models.BooleanField(default=False)
    ref_code = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    total_amount = models.FloatField()
    date_paid = models.DateTimeField(auto_now_add=True)
    stripe_charge_id = models.CharField(max_length=100)

    def __str__(self):
        return self.stripe_charge_id
    


    

digital_marketplace/books/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book, Chapter, Exercise
from django.http import Http404
from shopping_cart.models import Order, OrderItem 

OWNED='owned'
IN_CART='in_cart'
NOT_IN_CART='not_in_cart'


def check_book_relationship(request,book):
    print((request.user.userlibrary.books.all()))
    print(book)
    if book in request.user.userlibrary.books.all():
        pritn(OWNED)
        return OWNED
    order_qs = Order.objects.filter(user=request.user)
    print(request.user)
    if order_qs.exists():
        order=order_qs[0]
        order_item_qs = OrderItem.objects.filter(book=book)
        if order_item_qs.exists():
            order_item = order_item_qs[0]
            if order_item in order.items.all():
                print(IN_CART)
                return IN_CART
    print((request.user.userlibrary.books.all()))
    print(NOT_IN_CART)
    return NOT_IN_CART

def book_list(request):
    queryset = Book.objects.all()
    context = {
        'queryset': queryset
    }
    return render(request, 'book_list.html', context)

def book_detail(request, slug):
    book = get_object_or_404(Book, slug=slug)
    book_status = check_book_relationship(request, book)
    context={
        'book':book,
        'book_status': book_status
    }
    return render(request, 'book_detail.html', context)

def chapter_detail(request, book_slug, chapter_number):
    chapter_qs = Chapter.objects.filter(book__slug=book_slug).filter(chapter_number=chapter_number)
    chapter = chapter_qs[0]
    book_status = check_book_relationship(request, chapter.book)
    if chapter_qs.exists():
        context={
            'chapter':chapter,
            'book_status': book_status
        }
        return render(request, 'chapter_detail.html', context)
    return Http404

def exercise_detail(request, book_slug, chapter_number, exercise_number):
    exercise_qs = Exercise.objects.filter(chapter__book__slug=book_slug).filter(chapter__chapter_number=chapter_number).filter(exercise_number=exercise_number)
    exercise = exercise_qs[0]
    book_status = check_book_relationship(request, exercise.chapter.book)
    if exercise_qs.exists():
        context={
            'exercise': exercise,
            'book_status': book_status
        }
        return render(request, 'exercise_detail.html', context)
    return Http404

digital_marketplace/shopping_cart/views.py
from django.shortcuts import render, get_object_or_404
from books.models import Book
from django.http import HttpResponseRedirect
from .models import Order, OrderItem

def add_to_cart(request, book_slug):
    book = get_object_or_404(Book, slug=book_slug)
    order_item, created = OrderItem.objects.get_or_create(book=book)
    order, created = Order.objects.get_or_create(user=request.user)
    order.items.add(order_item)
    order.save()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

def remove_from_cart(request, book_slug):
    book= get_object_or_404(Book, slug=book_slug)
    order_item = get_object_or_404(OrderItem, book=book)
    order= get_object_or_404(Order, user=request.user)
    order.items.remove(order_item)
    order.save()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

digital_marketplace/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Digital Marketplace</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body>
<div class="container">
  {% include 'navbar.html' %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% block breadcrumb %}
      {% endblock breadcrumb %} 
    </ol>
  </nav>
  {% block content %}
  {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

digital_marketplace/templates/book_detail.html
{% extends 'base.html' %}
{% block breadcrumb%}
    <li class="breadcrumb-item" aria-current="page">
    <a href="{% url 'books:book-list' %}">Book-List</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{book}}</li>
{% endblock breadcrumb %}
{% block content %}
<div class="row">
<main class='col-md-4'>
    {% include 'book_snippet.html' with book=book book_status=book_status %}
</main>
<aside class='col-md-8'>
<div class="card" >
    <div class="card-header">
        Chapters
    </div>
    <ul class="list-group list-group-flush">
        {% for chapter in book.chapter_set.all %}
            <li class="list-group-item">
            <a href="{{ chapter.get_absolute_url }}">{{chapter.chapter_number}}.{{ chapter.title|title }}</a>
            </li>
        {% endfor %}   
    </ul>
</div>    
</aside>   
{% endblock content%}

digital_marketplace/templates/book_list.html
{% extends 'base.html' %}

{% block breadcrumb%}
    <li class="breadcrumb-item active" aria-current="page">Book-List</li>
{% endblock breadcrumb %}
{% block content %}
    <h1>This is a Book List</h1>
    <hr>
    {% for book in queryset %}
        <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">{{ book.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ book.publication_date }}</h6>
        {% for author in book.authors.all %}
        <p class="card-text">
        <span>{{ author }}</span> {% if book.authors.count > 1 %} | {% endif %}
        </p>
        {% endfor %}
        <a href="{{ book.get_absolute_url }}" class="card-link">{{ book }}</a>
    </div>
</div>
    {% endfor %}
{% endblock content%}

digital_marketplace/templates/book_snippet.html
<div class="card" style="width: 18rem;">
    <div class="card-header">
        {{ book.title|title }}
    </div>
    <img src="{{ book.cover.url }}" class="card-img-top" alt="...">
    <div class="card-body">
        <p class="card-text">Published: {{ book.publication_date }}</p>
    </div>
    <div class="card-footer">
    {% if book_status != 'owned' %}
        {% if book_status == 'in_cart' %}
            <a href="{% url 'cart:remove-from-cart' book.slug %}" class="btn btn-default btn-block">
                Remove From cart
            </a>
        {% else %}
            <a href="{% url 'cart:add-to-cart' book.slug %}" class="btn btn-warning btn-block">
                Add to Cart
            </a>
        {% endif %}
        </div>
        {% endif %}
</div>

digital_marketplace/templates/chapter_detail.html
{% extends 'base.html' %}
{% block breadcrumb%}
    <li class="breadcrumb-item" aria-current="page">
    <a href="{% url 'books:book-list' %}">Book-List</a></li>
    <li class="breadcrumb-item" aria-current="page">
    <a href="{{ chapter.book.get_absolute_url }}">{{ chapter.book.title }}</a></li>

    <li class="breadcrumb-item active" aria-current="page">{{ chapter }}</li>
{% endblock breadcrumb %}
{% block content %}
<div class="row">
<main class='col-md-4'>
    {% include 'book_snippet.html' with book=chapter.book %}
</main>
<aside class='col-md-8'>
<div class="card" >
    <div class="card-header">
        Exercises
    </div>
    <ul class="list-group list-group-flush">
        {% for exercise in chapter.exercise_set.all %}
            <li class="list-group-item">
            <a href="{{ exercise.get_absolute_url }}">{{exercise.exercise_number}}.{{ exercise|title }}</a>
            </li>
        {% endfor %}   
    </ul>
</div>    
</aside> 
{% endblock content%}  

digital_marketplace/templates/exercise_detail.html
{% extends 'base.html' %}
{% load static %}
{% block breadcrumb%}
    <li class="breadcrumb-item" aria-current="page">
    <a href="{% url 'books:book-list' %}">Book-List</a></li>
    <li class="breadcrumb-item" aria-current="page">
    <a href="{{ exercise.chapter.book.get_absolute_url }}">{{ exercise.chapter.book.title }}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
    <a href="{{ exercise.chapter.get_absolute_url }}">{{ exercise.chapter.title }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ exercise }}</li>

{% endblock breadcrumb %}
{% block content %}
    <div class="row">
<main class='col-md-4'>
    {% include 'book_snippet.html' with book=exercise.chapter.book %}
</main>
<aside class='col-md-8'>
<div class="card" >
    <div class="card-header">
        Solutions
    </div>
    {% if exercise.chapter.book in request.user.userlibrary.book_list %}
    {% for solution in exercise.solution_set.all %}
    <div class="accordion" id="toggle-{{ solution.solution_number }}">
        <div class="card">
            <div class="card-header" id="heading-{{solution.solution_number}}">
                <h2 class="mb-0">
                    <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse-{{solution.solution_number}}" aria-expanded="true" aria-controls="collapse-{{ solution.solution_number }}">
                        Solution: {{solution.solution_number}}
                    </button>
                </h2>
            </div>
            <div id="collapse-{{ solution.solution_number }}" class="collapse" aria-labelledby="heading-{{solution.solution_number}}" data-parent="#toggle-{{ solution.solution_number }}">
                <div class="card-body">
                 <img src="{{ solution.image.url }}" class="card-img-top" alt="...">
                </div>
            </div>
        </div> 
    </div>
    {% endfor %}
    {% else %}
    <div class="text-center">
        <h4>You dont have access to this book.
        <a href="#">Purchase This Book Now</a> to have access</h4>
        <img src="{% static 'images/lock.png' %}">
    </div>
    {% endif %}

</div>    
</aside> 
{% endblock content%}

digital_marketplace/templates/navbar.html
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
    <a class="navbar-brand" href="{% url 'books:book-list' %}">Marketplace</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample09">
      <ul class="navbar-nav mr-auto">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">Login</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">SignUp</a>
        </li>
      {% endif %}
      
      </ul>
      <form class="form-inline my-2 my-md-0">
        <input class="form-control" type="text" placeholder="Search" aria-label="Search">
      </form>
    </div>
  </nav>
</div>

digital_marketplace/templates/old_base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>